[package]
name = "les-systemes-de-lindenmayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burtle = {git = "https://github.com/klownie/Burtle", features = ["lindenmayer"]}

